# Classifying Penguins with Keras

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

2026-05-13 14:33:12.697593: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [ ]:
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [3]:
#drop nan rows
penguins = penguins.dropna()
penguins.shape

(333, 8)

In [4]:
penguins = penguins.sample(frac=1, random_state = 42).reset_index(drop=True)

In [5]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3250.0,39.5,16.7,178.0,True,False
1,3675.0,50.9,17.9,196.0,True,False
2,4000.0,42.1,19.1,195.0,False,True
3,4850.0,46.6,14.2,210.0,True,False
4,4050.0,41.1,18.2,192.0,False,True
...,...,...,...,...,...,...
328,4750.0,49.6,15.0,216.0,False,True
329,3900.0,37.2,19.4,184.0,False,True
330,3200.0,39.7,17.7,193.0,True,False
331,3950.0,45.2,17.8,198.0,True,False
332,3175.0,38.1,17.0,181.0,True,False

In [6]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.152778,0.269091,0.428571,0.101695,1.0,0.0
1,0.270833,0.683636,0.571429,0.406780,1.0,0.0
2,0.361111,0.363636,0.714286,0.389831,0.0,1.0
3,0.597222,0.527273,0.130952,0.644068,1.0,0.0
4,0.375000,0.327273,0.607143,0.338983,0.0,1.0
...,...,...,...,...,...,...
328,0.569444,0.636364,0.226190,0.745763,0.0,1.0
329,0.333333,0.185455,0.750000,0.203390,0.0,1.0
330,0.138889,0.276364,0.547619,0.355932,1.0,0.0
331,0.347222,0.476364,0.559524,0.440678,1.0,0.0
332,0.131944,0.218182,0.464286,0.152542,1.0,0.0

In [7]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)

In [8]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
#make sure the model activation is right for 3 categories, not sigmoid
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [9]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [11]:

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)
history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

/Users/kellyohata/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 93ms/step - accuracy: 0.3445 - loss: 1.0941 - val_accuracy: 0.4706 - val_loss: 1.0894
Epoch 2/100

/Users/kellyohata/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.3813 - loss: 1.0849 - val_accuracy: 0.3824 - val_loss: 1.0845
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4080 - loss: 1.0792 - val_accuracy: 0.3235 - val_loss: 1.0808
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4114 - loss: 1.0749 - val_accuracy: 0.3235 - val_loss: 1.0780
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4281 - loss: 1.0711 - val_accuracy: 0.4118 - val_loss: 1.0753
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4548 - loss: 1.0678 - val_accuracy: 0.3824 - val_loss: 1.0733
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4749 - loss: 1.0649 - val_accuracy: 0.5000 - val_loss: 1.0711
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5084 - loss: 1.0622 - val_accuracy: 0.4706 - val_loss: 1.0694
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5318 - loss: 1.0598 - val_accuracy: 0.5588 - val_loss: 1.0676
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5786 - loss: 1.0574 - val_accuracy: 0.5588 - val_loss: 1.0658
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5552 - loss: 1.0552 - val_accuracy: 0.5588 - val_loss: 1.0643
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5853 - loss: 1.0528 - val_accuracy: 0.5588 - val_loss: 1.0626
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5719 - loss: 1.0506 - val_accuracy: 0.5588 - val_loss: 1.0606
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5686 - loss: 1.0488 - val_accuracy: 0.5588 - val_loss: 1.0594
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5987 - loss: 1.0465 - val_accuracy: 0.5588 - val_loss: 1.0576
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5819 - loss: 1.0447 - val_accuracy: 0.5588 - val_loss: 1.0561
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6120 - loss: 1.0426 - val_accuracy: 0.5588 - val_loss: 1.0544
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6087 - loss: 1.0406 - val_accuracy: 0.5588 - val_loss: 1.0528
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6120 - loss: 1.0387 - val_accuracy: 0.5588 - val_loss: 1.0511
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6187 - loss: 1.0367 - val_accuracy: 0.5588 - val_loss: 1.0491
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6120 - loss: 1.0349 - val_accuracy: 0.5588 - val_loss: 1.0476
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6020 - loss: 1.0327 - val_accuracy: 0.5588 - val_loss: 1.0462
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6054 - loss: 1.0309 - val_accuracy: 0.5588 - val_loss: 1.0444
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6154 - loss: 1.0285 - val_accuracy: 0.5588 - val_loss: 1.0425
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6221 - loss: 1.0264 - val_accuracy: 0.5588 - val_loss: 1.0403
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6087 - loss: 1.0238 - val_accuracy: 0.5588 - val_loss: 1.0382
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6221 - loss: 1.0215 - val_accuracy: 0.5588 - val_loss: 1.0358
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6221 - loss: 1.0192 - val_accuracy: 0.5588 - val_loss: 1.0333
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6221 - loss: 1.0164 - val_accuracy: 0.5588 - val_loss: 1.0313
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6221 - loss: 1.0139 - val_accuracy: 0.5588 - val_loss: 1.0290
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6288 - loss: 1.0116 - val_accuracy: 0.5882 - val_loss: 1.0261
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6555 - loss: 1.0092 - val_accuracy: 0.5882 - val_loss: 1.0239
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6622 - loss: 1.0063 - val_accuracy: 0.6765 - val_loss: 1.0213
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6722 - loss: 1.0037 - val_accuracy: 0.7059 - val_loss: 1.0188
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6756 - loss: 1.0009 - val_accuracy: 0.7059 - val_loss: 1.0166
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6856 - loss: 0.9981 - val_accuracy: 0.7059 - val_loss: 1.0139
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6890 - loss: 0.9951 - val_accuracy: 0.7059 - val_loss: 1.0107
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7023 - loss: 0.9920 - val_accuracy: 0.7059 - val_loss: 1.0075
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7023 - loss: 0.9886 - val_accuracy: 0.7059 - val_loss: 1.0038
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6890 - loss: 0.9852 - val_accuracy: 0.7059 - val_loss: 1.0008
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7224 - loss: 0.9821 - val_accuracy: 0.7059 - val_loss: 0.9968
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7291 - loss: 0.9782 - val_accuracy: 0.7353 - val_loss: 0.9931
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7358 - loss: 0.9745 - val_accuracy: 0.7647 - val_loss: 0.9891
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7425 - loss: 0.9707 - val_accuracy: 0.7647 - val_loss: 0.9852
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7425 - loss: 0.9667 - val_accuracy: 0.7941 - val_loss: 0.9803
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7559 - loss: 0.9629 - val_accuracy: 0.7941 - val_loss: 0.9762
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7358 - loss: 0.9584 - val_accuracy: 0.7941 - val_loss: 0.9723
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7625 - loss: 0.9539 - val_accuracy: 0.7941 - val_loss: 0.9673
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7559 - loss: 0.9493 - val_accuracy: 0.7941 - val_loss: 0.9622
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7492 - loss: 0.9444 - val_accuracy: 0.7941 - val_loss: 0.9569
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7659 - loss: 0.9401 - val_accuracy: 0.7941 - val_loss: 0.9520
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7525 - loss: 0.9347 - val_accuracy: 0.7941 - val_loss: 0.9470
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7692 - loss: 0.9298 - val_accuracy: 0.7941 - val_loss: 0.9413
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7659 - loss: 0.9246 - val_accuracy: 0.7941 - val_loss: 0.9358
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7559 - loss: 0.9194 - val_accuracy: 0.7941 - val_loss: 0.9302
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7659 - loss: 0.9140 - val_accuracy: 0.7941 - val_loss: 0.9254
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7692 - loss: 0.9084 - val_accuracy: 0.7941 - val_loss: 0.9189
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7625 - loss: 0.9027 - val_accuracy: 0.7941 - val_loss: 0.9133
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7692 - loss: 0.8967 - val_accuracy: 0.7941 - val_loss: 0.9076
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7726 - loss: 0.8909 - val_accuracy: 0.7941 - val_loss: 0.9022
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7759 - loss: 0.8845 - val_accuracy: 0.7941 - val_loss: 0.8946
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7726 - loss: 0.8779 - val_accuracy: 0.7941 - val_loss: 0.8876
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7759 - loss: 0.8714 - val_accuracy: 0.7941 - val_loss: 0.8812
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7793 - loss: 0.8647 - val_accuracy: 0.7941 - val_loss: 0.8736
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7759 - loss: 0.8583 - val_accuracy: 0.7941 - val_loss: 0.8667
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7793 - loss: 0.8514 - val_accuracy: 0.7941 - val_loss: 0.8594
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7759 - loss: 0.8446 - val_accuracy: 0.7941 - val_loss: 0.8514
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7759 - loss: 0.8375 - val_accuracy: 0.7941 - val_loss: 0.8446
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7793 - loss: 0.8306 - val_accuracy: 0.7941 - val_loss: 0.8364
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7793 - loss: 0.8232 - val_accuracy: 0.7941 - val_loss: 0.8285
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7793 - loss: 0.8157 - val_accuracy: 0.7941 - val_loss: 0.8199
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7793 - loss: 0.8076 - val_accuracy: 0.7941 - val_loss: 0.8114
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7793 - loss: 0.7998 - val_accuracy: 0.7941 - val_loss: 0.8038
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7826 - loss: 0.7916 - val_accuracy: 0.7941 - val_loss: 0.7952
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7860 - loss: 0.7834 - val_accuracy: 0.7941 - val_loss: 0.7856
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7860 - loss: 0.7747 - val_accuracy: 0.7941 - val_loss: 0.7763
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.7662 - val_accuracy: 0.7941 - val_loss: 0.7663
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.7577 - val_accuracy: 0.7941 - val_loss: 0.7563
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.7487 - val_accuracy: 0.7941 - val_loss: 0.7462
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7893 - loss: 0.7394 - val_accuracy: 0.7941 - val_loss: 0.7351
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7893 - loss: 0.7297 - val_accuracy: 0.7941 - val_loss: 0.7243
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.7187 - val_accuracy: 0.7941 - val_loss: 0.7130
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.7080 - val_accuracy: 0.7941 - val_loss: 0.7020
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7893 - loss: 0.6971 - val_accuracy: 0.7941 - val_loss: 0.6901
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.6868 - val_accuracy: 0.7941 - val_loss: 0.6779
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.6771 - val_accuracy: 0.7941 - val_loss: 0.6682
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7893 - loss: 0.6672 - val_accuracy: 0.7941 - val_loss: 0.6569
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7893 - loss: 0.6573 - val_accuracy: 0.7941 - val_loss: 0.6465
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7893 - loss: 0.6482 - val_accuracy: 0.7941 - val_loss: 0.6359
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7893 - loss: 0.6389 - val_accuracy: 0.7941 - val_loss: 0.6245
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.6293 - val_accuracy: 0.7941 - val_loss: 0.6153
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7893 - loss: 0.6211 - val_accuracy: 0.7941 - val_loss: 0.6056
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.6122 - val_accuracy: 0.7941 - val_loss: 0.5952
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.6035 - val_accuracy: 0.7941 - val_loss: 0.5859
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7893 - loss: 0.5949 - val_accuracy: 0.7941 - val_loss: 0.5770
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.5860 - val_accuracy: 0.7941 - val_loss: 0.5672
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.5771 - val_accuracy: 0.7941 - val_loss: 0.5576
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.5680 - val_accuracy: 0.7941 - val_loss: 0.5474
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.5585 - val_accuracy: 0.7941 - val_loss: 0.5358
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.5483 - val_accuracy: 0.7941 - val_loss: 0.5251
11/11 - 0s - 6ms/step - accuracy: 0.7928 - loss: 0.5399

In [ ]:
model_logit_false = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_false.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.7926 - loss: 0.5320 - val_accuracy: 0.7941 - val_loss: 0.5003
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7893 - loss: 0.5152 - val_accuracy: 0.7941 - val_loss: 0.4875
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.5034 - val_accuracy: 0.7941 - val_loss: 0.4760
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7893 - loss: 0.4937 - val_accuracy: 0.7941 - val_loss: 0.4674
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7926 - loss: 0.4850 - val_accuracy: 0.7941 - val_loss: 0.4584
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4773 - val_accuracy: 0.7941 - val_loss: 0.4497
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4696 - val_accuracy: 0.7941 - val_loss: 0.4419
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7960 - loss: 0.4624 - val_accuracy: 0.7941 - val_loss: 0.4336
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4554 - val_accuracy: 0.7941 - val_loss: 0.4262
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4485 - val_accuracy: 0.7941 - val_loss: 0.4186
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4420 - val_accuracy: 0.7941 - val_loss: 0.4107
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4354 - val_accuracy: 0.7941 - val_loss: 0.4026
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4292 - val_accuracy: 0.7941 - val_loss: 0.3969
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.4231 - val_accuracy: 0.7941 - val_loss: 0.3900
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.4169 - val_accuracy: 0.7941 - val_loss: 0.3832
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.4108 - val_accuracy: 0.7941 - val_loss: 0.3767
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7960 - loss: 0.4044 - val_accuracy: 0.8529 - val_loss: 0.3682
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8060 - loss: 0.3986 - val_accuracy: 0.8235 - val_loss: 0.3628
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8227 - loss: 0.3928 - val_accuracy: 0.8529 - val_loss: 0.3556
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8261 - loss: 0.3870 - val_accuracy: 0.8529 - val_loss: 0.3492
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8361 - loss: 0.3809 - val_accuracy: 0.8824 - val_loss: 0.3440
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8462 - loss: 0.3757 - val_accuracy: 0.8824 - val_loss: 0.3375
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8495 - loss: 0.3697 - val_accuracy: 0.8824 - val_loss: 0.3311
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8528 - loss: 0.3641 - val_accuracy: 0.8824 - val_loss: 0.3260
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8696 - loss: 0.3584 - val_accuracy: 0.8824 - val_loss: 0.3209
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8729 - loss: 0.3530 - val_accuracy: 0.8824 - val_loss: 0.3148
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8763 - loss: 0.3480 - val_accuracy: 0.8824 - val_loss: 0.3105
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8863 - loss: 0.3426 - val_accuracy: 0.8824 - val_loss: 0.3063
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8863 - loss: 0.3375 - val_accuracy: 0.8824 - val_loss: 0.3008
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8896 - loss: 0.3331 - val_accuracy: 0.8824 - val_loss: 0.2952
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8930 - loss: 0.3284 - val_accuracy: 0.9118 - val_loss: 0.2905
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8896 - loss: 0.3229 - val_accuracy: 0.9118 - val_loss: 0.2847
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8997 - loss: 0.3183 - val_accuracy: 0.9118 - val_loss: 0.2801
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9097 - loss: 0.3135 - val_accuracy: 0.9118 - val_loss: 0.2755
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9064 - loss: 0.3091 - val_accuracy: 0.9118 - val_loss: 0.2708
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9030 - loss: 0.3047 - val_accuracy: 0.9118 - val_loss: 0.2662
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9130 - loss: 0.2997 - val_accuracy: 0.9118 - val_loss: 0.2610
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9164 - loss: 0.2960 - val_accuracy: 0.9412 - val_loss: 0.2565
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9231 - loss: 0.2910 - val_accuracy: 0.9412 - val_loss: 0.2525
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9231 - loss: 0.2867 - val_accuracy: 0.9412 - val_loss: 0.2476
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9331 - loss: 0.2835 - val_accuracy: 0.9412 - val_loss: 0.2442
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9298 - loss: 0.2786 - val_accuracy: 0.9412 - val_loss: 0.2397
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9331 - loss: 0.2757 - val_accuracy: 0.9412 - val_loss: 0.2359
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9398 - loss: 0.2709 - val_accuracy: 0.9412 - val_loss: 0.2324
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9398 - loss: 0.2673 - val_accuracy: 0.9412 - val_loss: 0.2293
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9398 - loss: 0.2637 - val_accuracy: 0.9706 - val_loss: 0.2244
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9398 - loss: 0.2595 - val_accuracy: 0.9412 - val_loss: 0.2216
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9431 - loss: 0.2571 - val_accuracy: 0.9412 - val_loss: 0.2179
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9498 - loss: 0.2524 - val_accuracy: 0.9706 - val_loss: 0.2142
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9431 - loss: 0.2495 - val_accuracy: 0.9706 - val_loss: 0.2106
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9498 - loss: 0.2453 - val_accuracy: 0.9706 - val_loss: 0.2073
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9565 - loss: 0.2420 - val_accuracy: 0.9706 - val_loss: 0.2038
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9565 - loss: 0.2387 - val_accuracy: 0.9706 - val_loss: 0.2004
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9565 - loss: 0.2348 - val_accuracy: 1.0000 - val_loss: 0.1973
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9565 - loss: 0.2312 - val_accuracy: 1.0000 - val_loss: 0.1940
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9599 - loss: 0.2282 - val_accuracy: 1.0000 - val_loss: 0.1906
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9699 - loss: 0.2240 - val_accuracy: 1.0000 - val_loss: 0.1876
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9599 - loss: 0.2218 - val_accuracy: 1.0000 - val_loss: 0.1844
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9632 - loss: 0.2174 - val_accuracy: 1.0000 - val_loss: 0.1809
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9699 - loss: 0.2148 - val_accuracy: 1.0000 - val_loss: 0.1776
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9666 - loss: 0.2112 - val_accuracy: 1.0000 - val_loss: 0.1742
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9699 - loss: 0.2084 - val_accuracy: 1.0000 - val_loss: 0.1715
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9732 - loss: 0.2046 - val_accuracy: 1.0000 - val_loss: 0.1686
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9732 - loss: 0.2012 - val_accuracy: 1.0000 - val_loss: 0.1656
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9732 - loss: 0.1988 - val_accuracy: 1.0000 - val_loss: 0.1629
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9732 - loss: 0.1964 - val_accuracy: 1.0000 - val_loss: 0.1600
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9732 - loss: 0.1920 - val_accuracy: 1.0000 - val_loss: 0.1569
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9732 - loss: 0.1898 - val_accuracy: 1.0000 - val_loss: 0.1540
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9732 - loss: 0.1863 - val_accuracy: 1.0000 - val_loss: 0.1516
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9732 - loss: 0.1836 - val_accuracy: 1.0000 - val_loss: 0.1489
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9732 - loss: 0.1805 - val_accuracy: 1.0000 - val_loss: 0.1461
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9732 - loss: 0.1779 - val_accuracy: 1.0000 - val_loss: 0.1433
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9766 - loss: 0.1752 - val_accuracy: 1.0000 - val_loss: 0.1409
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9766 - loss: 0.1720 - val_accuracy: 1.0000 - val_loss: 0.1385
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9766 - loss: 0.1691 - val_accuracy: 1.0000 - val_loss: 0.1357
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1664 - val_accuracy: 1.0000 - val_loss: 0.1333
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9732 - loss: 0.1641 - val_accuracy: 1.0000 - val_loss: 0.1309
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1612 - val_accuracy: 1.0000 - val_loss: 0.1287
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1581 - val_accuracy: 1.0000 - val_loss: 0.1271
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1561 - val_accuracy: 1.0000 - val_loss: 0.1240
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1534 - val_accuracy: 1.0000 - val_loss: 0.1222
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1512 - val_accuracy: 1.0000 - val_loss: 0.1197
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1482 - val_accuracy: 1.0000 - val_loss: 0.1170
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1458 - val_accuracy: 1.0000 - val_loss: 0.1149
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9766 - loss: 0.1438 - val_accuracy: 1.0000 - val_loss: 0.1132
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1415 - val_accuracy: 1.0000 - val_loss: 0.1107
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9732 - loss: 0.1394 - val_accuracy: 1.0000 - val_loss: 0.1098
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9766 - loss: 0.1366 - val_accuracy: 1.0000 - val_loss: 0.1071
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.1344 - val_accuracy: 1.0000 - val_loss: 0.1055
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9799 - loss: 0.1324 - val_accuracy: 1.0000 - val_loss: 0.1032
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.1305 - val_accuracy: 1.0000 - val_loss: 0.1009
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9732 - loss: 0.1299 - val_accuracy: 1.0000 - val_loss: 0.0994
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9799 - loss: 0.1262 - val_accuracy: 1.0000 - val_loss: 0.0985
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9799 - loss: 0.1242 - val_accuracy: 1.0000 - val_loss: 0.0957
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9833 - loss: 0.1221 - val_accuracy: 1.0000 - val_loss: 0.0943
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9833 - loss: 0.1206 - val_accuracy: 1.0000 - val_loss: 0.0944
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.1182 - val_accuracy: 1.0000 - val_loss: 0.0919
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9799 - loss: 0.1161 - val_accuracy: 1.0000 - val_loss: 0.0894
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9799 - loss: 0.1149 - val_accuracy: 1.0000 - val_loss: 0.0881
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.1124 - val_accuracy: 1.0000 - val_loss: 0.0861
11/11 - 0s - 6ms/step - accuracy: 0.9850 - loss: 0.1082

In [13]:
model_logit_false.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

array([[9.34798002e-01, 4.65603620e-02, 1.86416432e-02],
       [1.40357884e-02, 7.94725239e-01, 1.91238940e-01],
       [9.79492784e-01, 1.41025167e-02, 6.40468020e-03],
       [2.57308802e-05, 5.55673381e-03, 9.94417489e-01],
       [9.80454385e-01, 1.34193627e-02, 6.12621848e-03],
       [2.32068766e-02, 8.06900144e-01, 1.69892997e-01],
       [2.76306540e-01, 5.66590786e-01, 1.57102600e-01],
       [2.05340533e-04, 6.60905764e-02, 9.33704019e-01],
       [1.24865037e-05, 1.18632428e-02, 9.88124311e-01],
       [1.48922816e-04, 1.47480210e-02, 9.85103011e-01],
       [7.07616508e-01, 2.19066262e-01, 7.33170807e-02],
       [9.97629046e-01, 1.36810343e-03, 1.00282242e-03],
       [4.92099613e-01, 3.89296681e-01, 1.18603610e-01],
       [9.76954281e-01, 1.59106720e-02, 7.13492325e-03],
       [5.16414605e-02, 7.72298813e-01, 1.76059693e-01],
       [9.62233663e-01, 2.65052337e-02, 1.12610077e-02],
       [9.81745124e-01, 1.25040589e-02, 5.75073482e-03],
       [1.94537788e-05, 2.97242985e-03, 9.97008085e-01],
       [9.81511712e-01, 1.26695847e-02, 5.81884803e-03],
       [3.62190679e-02, 7.89980471e-01, 1.73800573e-01],
       [9.31690991e-01, 4.88331094e-02, 1.94757767e-02],
       [9.73965228e-01, 1.80480462e-02, 7.98671879e-03],
       [1.67955570e-02, 7.79537141e-01, 2.03667343e-01],
       [8.00183625e-06, 1.73542800e-03, 9.98256624e-01],
       [9.55844045e-01, 3.11461706e-02, 1.30096721e-02],
       [9.55809653e-01, 3.11701726e-02, 1.30201885e-02],
       [1.03140110e-05, 2.42553069e-03, 9.97564137e-01],
       [3.70222814e-02, 7.87936091e-01, 1.75041601e-01],
       [1.19021051e-05, 1.20499339e-02, 9.87938166e-01],
       [1.26104265e-01, 6.98267102e-01, 1.75628662e-01],
       [5.33576022e-05, 8.89461767e-03, 9.91052032e-01],
       [2.81433836e-02, 8.00158381e-01, 1.71698198e-01],
       [9.76891875e-01, 1.59553383e-02, 7.15284515e-03],
       [9.68317628e-01, 2.21052263e-02, 9.57721099e-03],
       [1.34718679e-02, 7.64478266e-01, 2.22049803e-01],
       [1.25562206e-01, 6.98884010e-01, 1.75553694e-01],
       [7.15464586e-03, 2.12566152e-01, 7.80279100e-01],
       [4.73085311e-06, 3.29247722e-03, 9.96702850e-01],
       [9.87359583e-01, 8.54935125e-03, 4.09099087e-03],
       [9.80442464e-01, 1.34278992e-02, 6.12970861e-03],
       [9.85854864e-01, 9.60453041e-03, 4.54055984e-03],
       [9.81613457e-01, 1.25974482e-02, 5.78917796e-03],
       [1.37528390e-04, 5.42559065e-02, 9.45606530e-01],
       [3.64719963e-05, 1.93213520e-03, 9.98031378e-01],
       [9.87764359e-01, 8.26621428e-03, 3.96938762e-03],
       [9.54181612e-01, 3.23516317e-02, 1.34667652e-02],
       [7.43739530e-02, 7.48309314e-01, 1.77316621e-01],
       [9.89572346e-01, 7.00536324e-03, 3.42228147e-03],
       [9.95522678e-01, 2.83816480e-03, 1.63919234e-03],
       [3.02573703e-02, 6.83036625e-01, 2.86705881e-01],
       [9.82574642e-01, 1.19170099e-02, 5.50837535e-03],
       [3.22040542e-05, 2.24021394e-02, 9.77565587e-01],
       [3.61779094e-05, 9.56247095e-03, 9.90401268e-01],
       [9.94827509e-01, 3.34258750e-03, 1.82994653e-03],
       [9.68520284e-01, 2.19609402e-02, 9.51877888e-03],
       [7.21785997e-04, 1.28668308e-01, 8.70609820e-01],
       [8.78605366e-01, 8.83835703e-02, 3.30109634e-02],
       [9.91568983e-01, 5.62143093e-03, 2.80960067e-03],
       [1.04954506e-05, 1.10293264e-02, 9.88960028e-01],
       [1.40855946e-06, 9.03087144e-04, 9.99095559e-01],
       [3.66971850e-01, 4.91009444e-01, 1.42018646e-01],
       [2.66285837e-02, 8.00684094e-01, 1.72687382e-01],
       [4.93216179e-02, 7.74854064e-01, 1.75824314e-01],
       [9.85179842e-01, 1.00790896e-02, 4.74101631e-03],
       [9.96621192e-01, 2.05832371e-03, 1.32038968e-03],
       [2.56690197e-02, 8.03475857e-01, 1.70855179e-01],
       [9.58442509e-01, 2.92506926e-02, 1.23067386e-02],
       [1.60878753e-05, 6.61050901e-03, 9.93373394e-01],
       [9.69481945e-01, 2.12681890e-02, 9.24987253e-03],
       [6.76466763e-01, 2.43370026e-01, 8.01632851e-02],
       [9.87287819e-01, 8.59959051e-03, 4.11252445e-03],
       [9.90778685e-01, 6.16804557e-03, 3.05329030e-03],
       [1.49439747e-05, 1.98588055e-02, 9.80126143e-01],
       [2.07281299e-02, 7.97349036e-01, 1.81922823e-01],
       [4.80804738e-05, 4.82444745e-03, 9.95127320e-01],
       [7.44339122e-05, 1.01344297e-02, 9.89791095e-01],
       [9.94264901e-01, 3.75586795e-03, 1.97923626e-03],
       [9.95592833e-01, 2.78763380e-03, 1.61949254e-03],
       [9.92678404e-01, 4.85702977e-03, 2.46457150e-03],
       [3.20884574e-04, 1.02468438e-01, 8.97210717e-01],
       [9.09614623e-01, 6.52047992e-02, 2.51805633e-02],
       [9.90634143e-01, 6.26812130e-03, 3.09765548e-03],
       [2.00280963e-04, 9.90905426e-03, 9.89890635e-01],
       [9.62277234e-01, 2.64716856e-02, 1.12509700e-02],
       [1.07646130e-01, 7.15786457e-01, 1.76567316e-01],
       [1.51302834e-06, 5.04558347e-03, 9.94952857e-01],
       [9.94817078e-01, 3.35019431e-03, 1.83274795e-03],
       [1.28253177e-02, 6.95195615e-01, 2.91979045e-01],
       [7.14931113e-04, 2.34454721e-02, 9.75839555e-01],
       [1.85468416e-05, 2.51382752e-03, 9.97467577e-01],
       [7.37219307e-06, 2.35735113e-03, 9.97635245e-01],
       [7.00394437e-02, 7.52747059e-01, 1.77213520e-01],
       [9.62018132e-01, 2.66552120e-02, 1.13266874e-02],
       [9.73515570e-01, 1.83702875e-02, 8.11416470e-03],
       [9.85437572e-01, 9.89785139e-03, 4.66458267e-03],
       [9.82353508e-01, 1.20734088e-02, 5.57306455e-03],
       [9.91701841e-01, 5.52959880e-03, 2.76842341e-03],
       [9.06017794e-06, 1.38421834e-03, 9.98606682e-01],
       [9.52340245e-01, 3.36940102e-02, 1.39657781e-02],
       [9.95218694e-01, 3.05776903e-03, 1.72350497e-03],
       [8.93343031e-01, 7.73314163e-02, 2.93256063e-02],
       [4.57762145e-02, 7.78821290e-01, 1.75402507e-01],
       [1.51300104e-02, 7.43002474e-01, 2.41867512e-01],
       [9.48719084e-01, 3.63377109e-02, 1.49432486e-02],
       [1.10615685e-04, 4.46384735e-02, 9.55250800e-01],
       [9.76731539e-01, 1.60696916e-02, 7.19870441e-03],
       [1.42377457e-05, 1.80064011e-02, 9.81979311e-01],
       [3.55528464e-05, 2.57082768e-02, 9.74256277e-01],
       [9.81227636e-01, 1.28708864e-02, 5.90155972e-03],
       [2.65407754e-04, 7.42168799e-02, 9.25517738e-01],
       [9.77325797e-01, 1.56457722e-02, 7.02852616e-03],
       [1.85007192e-02, 7.71316350e-01, 2.10182995e-01],
       [6.25067711e-01, 2.49996468e-01, 1.24935798e-01],
       [6.02194108e-04, 1.24495097e-01, 8.74902666e-01],
       [6.87957026e-06, 9.18780628e-04, 9.99074340e-01],
       [1.73334029e-05, 2.29621003e-03, 9.97686505e-01],
       [9.52152312e-01, 3.38309817e-02, 1.40166692e-02],
       [2.89626169e-05, 3.21666198e-03, 9.96754408e-01],
       [6.53357089e-01, 2.61380702e-01, 8.52621123e-02],
       [1.86501275e-05, 1.49999475e-02, 9.84981418e-01],
       [9.92749572e-01, 4.80808644e-03, 2.44229636e-03],
       [3.14516510e-05, 2.42035575e-02, 9.75764930e-01],
       [6.75655380e-02, 7.55351663e-01, 1.77082703e-01],
       [9.93053913e-01, 4.59920615e-03, 2.34695640e-03],
       [9.90231514e-01, 6.54732762e-03, 3.22104385e-03],
       [6.58943364e-03, 6.61477625e-01, 3.31932932e-01],
       [9.90891576e-01, 6.08986616e-03, 3.01858038e-03],
       [9.91149366e-01, 5.91154071e-03, 2.93923239e-03],
       [9.39057708e-01, 4.34127860e-02, 1.75293870e-02],
       [2.01570356e-06, 5.76660410e-03, 9.94231403e-01],
       [9.56171691e-01, 3.09076477e-02, 1.29206888e-02],
       [9.95733857e-01, 2.68647564e-03, 1.57969911e-03],
       [2.63558468e-05, 2.25227326e-02, 9.77450907e-01],
       [9.77586925e-01, 1.54595077e-02, 6.95359148e-03],
       [9.85259235e-01, 1.00232111e-02, 4.71746689e-03],
       [9.88201261e-01, 7.96100590e-03, 3.83781223e-03],
       [2.31942558e-05, 6.63775718e-03, 9.93339062e-01],
       [6.28975987e-01, 2.80513674e-01, 9.05102640e-02],
       [1.35662153e-01, 6.89525187e-01, 1.74812645e-01],
       [9.72017288e-01, 1.94450822e-02, 8.53750855e-03],
       [9.73492503e-01, 1.83868967e-02, 8.12072773e-03],
       [2.69794691e-05, 2.21902411e-02, 9.77782845e-01],
       [9.88733351e-01, 7.58961216e-03, 3.67698097e-03],
       [5.67572284e-03, 8.40018332e-01, 1.54305831e-01],
       [5.83673973e-05, 7.89557211e-03, 9.92046177e-01],
       [1.06057949e-01, 7.17243612e-01, 1.76698372e-01],
       [2.50881931e-05, 8.58012959e-03, 9.91394758e-01],
       [1.72030050e-02, 8.01583111e-01, 1.81213856e-01],
       [1.96252204e-05, 1.89325549e-02, 9.81047750e-01],
       [1.46051125e-05, 1.82507769e-03, 9.98160243e-01],
       [2.18863468e-04, 7.34815374e-02, 9.26299512e-01],
       [1.27987214e-05, 1.13288136e-02, 9.88658309e-01],
       [9.75217342e-01, 1.71517003e-02, 7.63090886e-03],
       [9.44888771e-01, 3.91377024e-02, 1.59735288e-02],
       [3.54533549e-05, 2.37433407e-02, 9.76221144e-01],
       [4.66437807e-04, 2.34281700e-02, 9.76105392e-01],
       [4.26134065e-05, 2.77642217e-02, 9.72193241e-01],
       [9.78470206e-01, 1.48301059e-02, 6.69966405e-03],
       [3.70722206e-04, 8.56248364e-02, 9.14004445e-01],
       [1.47200527e-03, 1.66759580e-01, 8.31768334e-01],
       [9.64665890e-01, 2.47401726e-02, 1.05939992e-02],
       [4.21278663e-02, 7.82992542e-01, 1.74879536e-01],
       [5.93072660e-02, 7.64049172e-01, 1.76643640e-01],
       [1.58554912e-02, 6.70514166e-01, 3.13630313e-01],
       [5.51330631e-05, 9.96467937e-03, 9.89980102e-01],
       [2.58698012e-04, 5.38822785e-02, 9.45858955e-01],
       [2.50233115e-05, 6.81176921e-03, 9.93163168e-01],
       [1.34453629e-04, 6.93471637e-03, 9.92930830e-01],
       [1.77453876e-05, 2.05692779e-02, 9.79412854e-01],
       [8.05777013e-01, 1.43519402e-01, 5.07036410e-02],
       [9.94337022e-01, 3.70262121e-03, 1.96031784e-03],
       [2.62101239e-05, 8.51136446e-03, 9.91462350e-01],
       [2.57297903e-02, 8.03393006e-01, 1.70877263e-01],
       [9.24503386e-01, 5.41450493e-02, 2.13516355e-02],
       [4.57170345e-02, 7.78888226e-01, 1.75394773e-01],
       [4.86700051e-02, 7.75577426e-01, 1.75752640e-01],
       [9.92176473e-01, 5.20238699e-03, 2.62111006e-03],
       [9.87624884e-01, 8.36378895e-03, 4.01134230e-03],
       [9.60470736e-01, 2.77786925e-02, 1.17504615e-02],
       [9.53489959e-01, 3.28553654e-02, 1.36546940e-02],
       [4.40195762e-02, 7.80817628e-01, 1.75162807e-01],
       [9.77961063e-01, 1.51927453e-02, 6.84611127e-03],
       [1.65788442e-04, 1.07305897e-02, 9.89103675e-01],
       [4.77531254e-02, 7.76599407e-01, 1.75647393e-01],
       [9.85002995e-01, 1.02035981e-02, 4.79344139e-03],
       [8.96513171e-04, 1.80486798e-01, 8.18616748e-01],
       [9.46403816e-06, 2.90179020e-03, 9.97088671e-01],
       [8.98946881e-01, 7.31409118e-02, 2.79122181e-02],
       [6.06368631e-02, 7.62609601e-01, 1.76753506e-01],
       [9.89503086e-01, 7.05353776e-03, 3.44336336e-03],
       [7.34023526e-02, 7.49238610e-01, 1.77358940e-01],
       [8.96787643e-01, 7.47226104e-02, 2.84897834e-02],
       [2.38397770e-05, 1.86606441e-02, 9.81315434e-01],
       [4.12929624e-01, 4.53292578e-01, 1.33777753e-01],
       [7.87947502e-05, 4.12199274e-02, 9.58701253e-01],
       [9.86370683e-01, 9.24240611e-03, 4.38689301e-03],
       [9.85672712e-01, 9.73255467e-03, 4.59474092e-03],
       [9.89116967e-01, 7.32236309e-03, 3.56074120e-03],
       [1.07427713e-05, 6.59394776e-04, 9.99329865e-01],
       [9.75363076e-01, 1.70474984e-02, 7.58941891e-03],
       [5.00877377e-06, 2.20447872e-03, 9.97790456e-01],
       [9.91276741e-01, 5.82339847e-03, 2.89991754e-03],
       [2.21097529e-01, 6.13773465e-01, 1.65128931e-01],
       [9.87918019e-01, 8.15880019e-03, 3.92313953e-03],
       [9.82205153e-01, 1.21783596e-02, 5.61642740e-03],
       [6.59407942e-06, 8.22557509e-03, 9.91767645e-01],
       [6.73575698e-07, 4.12001554e-03, 9.95879292e-01],
       [1.25681645e-05, 1.42553896e-02, 9.85731959e-01],
       [2.95124978e-01, 5.35075903e-01, 1.69798985e-01],
       [9.90305424e-01, 6.49613282e-03, 3.19846161e-03],
       [9.51940835e-01, 3.39720361e-02, 1.40871657e-02],
       [4.85948203e-06, 1.38029468e-03, 9.98614728e-01],
       [1.37893265e-04, 4.83146161e-02, 9.51547563e-01],
       [9.89283502e-01, 7.20631797e-03, 3.51012847e-03],
       [9.95143116e-01, 3.11261718e-03, 1.74424832e-03],
       [3.00192460e-02, 7.97713697e-01, 1.72266945e-01],
       [9.84830379e-01, 1.03250192e-02, 4.84450301e-03],
       [4.01183934e-06, 9.48062260e-03, 9.90515351e-01],
       [9.93259251e-01, 4.45827236e-03, 2.28237500e-03],
       [9.41517130e-02, 7.28643417e-01, 1.77204743e-01],
       [1.37360513e-01, 6.87985182e-01, 1.74654275e-01],
       [5.27268797e-02, 7.71113276e-01, 1.76159739e-01],
       [6.70400023e-01, 2.48041138e-01, 8.15587565e-02],
       [2.20143938e-05, 1.96696036e-02, 9.80308414e-01],
       [4.09638673e-01, 4.56068456e-01, 1.34293005e-01],
       [2.83636946e-05, 5.31193335e-03, 9.94659662e-01],
       [1.07084225e-05, 1.34148654e-02, 9.86574471e-01],
       [8.97315621e-01, 7.43427724e-02, 2.83415280e-02],
       [6.59707002e-04, 1.27769604e-01, 8.71570647e-01],
       [9.79243279e-01, 1.42799532e-02, 6.47676177e-03],
       [9.83034492e-01, 1.15918946e-02, 5.37360832e-03],
       [2.20816844e-04, 1.37636652e-02, 9.86015439e-01],
       [9.87896860e-01, 8.17359705e-03, 3.92951490e-03],
       [1.31727080e-04, 5.49744293e-02, 9.44893837e-01],
       [9.78084803e-01, 1.51046719e-02, 6.81057572e-03],
       [9.23245443e-06, 1.05743716e-02, 9.89416420e-01],
       [1.24631459e-02, 7.48004913e-01, 2.39531875e-01],
       [9.54927385e-01, 3.18063274e-02, 1.32663464e-02],
       [1.52026936e-01, 6.74546182e-01, 1.73426837e-01],
       [6.33941730e-04, 1.07381038e-01, 8.91984999e-01],
       [2.22306941e-02, 7.98401117e-01, 1.79368094e-01],
       [9.21521723e-01, 5.63552678e-02, 2.21229549e-02],
       [2.02703322e-05, 1.85416471e-02, 9.81437981e-01],
       [4.41906741e-05, 2.64645624e-03, 9.97309327e-01],
       [9.93410140e-06, 1.21107232e-02, 9.87879276e-01],
       [9.95076299e-01, 3.16117262e-03, 1.76251156e-03],
       [9.10162091e-01, 6.47823736e-02, 2.50555612e-02],
       [8.33084285e-01, 1.22765966e-01, 4.41497564e-02],
       [4.34407499e-04, 1.43064065e-02, 9.85259116e-01],
       [3.54273012e-04, 1.00100227e-02, 9.89635587e-01],
       [7.08979769e-06, 9.87381767e-03, 9.90119159e-01],
       [5.63180089e-01, 3.32553983e-01, 1.04265876e-01],
       [1.29551292e-04, 3.08873095e-02, 9.68983173e-01],
       [9.61890519e-01, 2.67528370e-02, 1.13567123e-02],
       [9.77252543e-01, 1.56979188e-02, 7.04948278e-03],
       [3.66671011e-04, 8.70030969e-02, 9.12630260e-01],
       [9.83636320e-01, 1.11669069e-02, 5.19683212e-03],
       [9.59384263e-01, 2.85709575e-02, 1.20449010e-02],
       [9.96050954e-01, 2.46018008e-03, 1.48884417e-03],
       [9.92606997e-01, 4.90617286e-03, 2.48691672e-03],
       [9.73738790e-01, 1.82102807e-02, 8.05091672e-03],
       [1.13631344e-04, 2.77956971e-03, 9.97106731e-01],
       [9.89526331e-01, 7.03729875e-03, 3.43625667e-03],
       [5.60572185e-02, 7.67513156e-01, 1.76429659e-01],
       [3.41616333e-01, 5.12074471e-01, 1.46309167e-01],
       [1.45534053e-04, 5.64284213e-02, 9.43426013e-01],
       [2.56325360e-02, 8.03525627e-01, 1.70841858e-01],
       [4.65815174e-05, 6.39815861e-03, 9.93555307e-01],
       [3.31410411e-05, 4.15679254e-03, 9.95809972e-01],
       [1.92335610e-05, 1.26597495e-03, 9.98714745e-01],
       [1.20186405e-02, 7.17090845e-01, 2.70890474e-01],
       [2.07902514e-04, 1.16017787e-02, 9.88190293e-01],
       [1.92284673e-01, 6.38820410e-01, 1.68894812e-01],
       [4.50356118e-02, 7.62304306e-01, 1.92660123e-01],
       [3.91036682e-02, 7.86529362e-01, 1.74366936e-01],
       [2.71070865e-04, 1.58437565e-02, 9.83885169e-01],
       [7.25945501e-05, 3.81580330e-02, 9.61769342e-01],
       [9.90741730e-01, 6.19364157e-03, 3.06464406e-03],
       [6.44524607e-06, 1.61841663e-03, 9.98375058e-01],
       [1.56277747e-05, 1.17500348e-03, 9.98809278e-01],
       [4.74016997e-05, 2.62319949e-02, 9.73720551e-01],
       [9.44784999e-01, 3.92193012e-02, 1.59957670e-02],
       [9.94488358e-01, 3.59121012e-03, 1.92043965e-03],
       [8.17353785e-01, 1.34699404e-01, 4.79467809e-02],
       [9.85208273e-01, 1.00590810e-02, 4.73258365e-03],
       [9.95855451e-01, 2.59948219e-03, 1.54508161e-03],
       [1.63341509e-04, 1.57663189e-02, 9.84070301e-01],
       [9.90929961e-01, 6.06322428e-03, 3.00674234e-03],
       [2.79705255e-05, 4.30141808e-03, 9.95670617e-01],
       [9.82680857e-01, 1.18418802e-02, 5.47726685e-03],
       [9.82331574e-01, 1.20889293e-02, 5.57947857e-03],
       [3.07916169e-04, 9.93560702e-02, 9.00335968e-01],
       [3.44634736e-06, 8.64039059e-04, 9.99132514e-01],
       [9.91138041e-01, 5.91928093e-03, 2.94268085e-03],
       [9.80218470e-01, 1.35868164e-02, 6.19461248e-03],
       [4.47070934e-02, 7.80033767e-01, 1.75259203e-01],
       [1.32368950e-05, 1.57744903e-02, 9.84212339e-01],
       [3.53124663e-02, 7.91082442e-01, 1.73605070e-01],
       [6.64708674e-01, 2.52518624e-01, 8.27726871e-02],
       [3.05089727e-02, 7.97084570e-01, 1.72406495e-01],
       [3.70102425e-05, 2.76253354e-02, 9.72337663e-01],
       [9.84096169e-01, 1.08423634e-02, 5.06135635e-03],
       [9.12849188e-01, 6.27864450e-02, 2.43643951e-02],
       [3.16065816e-05, 2.50103734e-02, 9.74958062e-01],
       [3.11111253e-05, 2.44465843e-02, 9.75522220e-01],
       [1.35557884e-02, 6.78414643e-01, 3.08029532e-01],
       [8.26287433e-05, 8.44030268e-03, 9.91477013e-01],
       [1.20826776e-03, 1.77255765e-01, 8.21535885e-01],
       [9.84020770e-01, 1.08955391e-02, 5.08358516e-03],
       [9.91222620e-01, 5.86080924e-03, 2.91661057e-03],
       [1.87516325e-05, 1.84118319e-02, 9.81569469e-01],
       [4.70354105e-04, 1.20987162e-01, 8.78542364e-01],
       [9.89906132e-01, 6.77334331e-03, 3.32052144e-03],
       [2.07378776e-04, 2.39594094e-02, 9.75833237e-01],
       [1.35622323e-01, 6.89619720e-01, 1.74757957e-01],
       [1.15092516e-04, 1.20041752e-02, 9.87880707e-01],
       [4.61768843e-02, 7.78368950e-01, 1.75454214e-01],
       [1.99538827e-05, 2.98596080e-03, 9.96994197e-01],
       [3.99862751e-02, 7.85489142e-01, 1.74524635e-01],
       [3.36923695e-05, 2.61416174e-02, 9.73824680e-01],
       [9.84225273e-01, 1.07513983e-02, 5.02330996e-03],
       [2.44347266e-05, 4.40813601e-03, 9.95567322e-01],
       [9.92507577e-01, 4.97446163e-03, 2.51792627e-03],
       [9.88361537e-01, 7.84909353e-03, 3.78943444e-03],
       [1.50176238e-05, 4.64899885e-03, 9.95335937e-01],
       [9.69068885e-01, 2.15656236e-02, 9.36544407e-03],
       [1.71398669e-02, 8.01505864e-01, 1.81354225e-01],
       [9.88367796e-01, 7.84467254e-03, 3.78752011e-03],
       [1.94888227e-04, 8.13973248e-02, 9.18407798e-01],
       [9.95878100e-01, 2.58335983e-03, 1.53862406e-03],
       [8.67498636e-01, 9.67152938e-02, 3.57860439e-02],
       [3.72965410e-02, 7.88681805e-01, 1.74021661e-01],
       [9.68723834e-01, 2.18142159e-02, 9.46190301e-03]], dtype=float32)

In [14]:
penguins['species']

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

In [15]:
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)